In [8]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# Load the dataset
iris = load_iris()

# Access data and targets
x = iris.data
y = iris.target
x_name = iris.feature_names
y_name = iris.target_names

#Feature Matrix as Numpy array
print("Feature Matrix as Numpy array: \n", np.array(x))

#Compute: Mean Median Standard deviation Variance (for each feature)
mean = np.mean(x, axis = 0)
median = np.median(x, axis = 0)
std = np.std(x, axis = 0)
variance = np.var(x, axis = 0)
print("\nCompute: Mean Median Standard deviation Variance (for each feature):\n")
print("Mean: ", mean)
print("Median: ", median)
print("Standard deviation: ", std)
print("Variance: ", variance)

#Identify: Which feature has highest variability and why it matters in ML
feature_with_highest_variability = np.argmax(variance)
print("\nFeature with highest variability: ", x_name[feature_with_highest_variability])
print("Highest variability: ", variance[feature_with_highest_variability])

print("\nWhy variability matters in ML:")
print("""Variability is all about understanding how spread out or clustered data points are in a dataset. 
In statistics, the variability is also known as dispersion, scatter, or spread. 
A low variability represents the data clustered around a center, while high variability indicates the widely spread data from the center.
A high variance model is prone to overfitting, which means it captures the noise and the specific patterns of the training data but fails to generalize well to new and unseen data.
A low-variance model is more stable and consistent, but it may underfit the data, which means it misses some significant features or relationships that could improve its performance.
The goal of any Machine Learning model is to find a balance between variance and bias, where Variability is key to the Bias-Variance Tradeoff in machine learning, which balances model accuracy and flexibility.""")

#Convert any one feature into shape (n,1) and explain why ML models expect this format
feature_in_n1_shape = x[:,0].reshape(-1,1)
print("\nOne feature into shape (n,1):\n", feature_in_n1_shape)

print("""\nMachine learning (ML) models expect input data in an (n, 1) format when dealing with a single feature because they are designed for matrix operations.
Most ML algorithms operate on 2D arrays (matrices), where the first dimension represents samples (n) and the second represents features (1). 
A 1D array of shape (n,) is mathematically ambiguous to these models as it lacks the explicit "feature" dimension required for matrix multiplication.
""")


Feature Matrix as Numpy array: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [10]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# Load the dataset
iris = load_iris()

# Access data and targets
x = iris.data
y = iris.target
x_name = iris.feature_names
y_name = iris.target_names

df = pd.DataFrame(x)

#Extract: First 100 samples & Only last 2 features
print("First 100 samples & Only last 2 features: \n", df.iloc[:100, -2:])

#2. Use boolean masking: Select samples where petal length is greater than dataset mean
# print(x_name[2]) # petal length (cm) is on index 2
df_petal_length_is_grether_than_mean = df.loc[df[2]>df[2].mean()]
print(df_petal_length_is_grether_than_mean)

#3. Count selected samples
print("Count of selected samples:", len(df_petal_length_is_grether_than_mean))

#4. Explain how this relates to feature-based filtering in ML
print("""\nFeature Engineering is the process of selecting, creating or modifying features like input variables or data 
to help machine learning models learn patterns more effectively. Feature selection is part of the feature engineering process, 
in which data scientists select the most relevant features of a dataset to use when building and training a machine learning (ML) model.
By reducing the feature space to a selected subset, feature selection improves AI model performance while lowering its computational demands. """)



First 100 samples & Only last 2 features: 
       2    3
0   1.4  0.2
1   1.4  0.2
2   1.3  0.2
3   1.5  0.2
4   1.4  0.2
..  ...  ...
95  4.2  1.2
96  4.2  1.3
97  4.3  1.3
98  3.0  1.1
99  4.1  1.3

[100 rows x 2 columns]
       0    1    2    3
50   7.0  3.2  4.7  1.4
51   6.4  3.2  4.5  1.5
52   6.9  3.1  4.9  1.5
53   5.5  2.3  4.0  1.3
54   6.5  2.8  4.6  1.5
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[93 rows x 4 columns]
Count of selected samples: 93

Feature Engineering is the process of selecting, creating or modifying features like input variables or data 
to help machine learning models learn patterns more effectively. Feature selection is part of the feature engineering process, 
in which data scientists select the most relevant features of a dataset to use when building and training a machine learning (ML) model.
By reducing the feature space to a selected subset, feature

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [3]:
import numpy as np
from sklearn.datasets import load_iris

# Load the dataset
iris = load_iris()

x = iris.data
y = iris.target

x_names = iris.feature_names
y_names = iris.target_names

# Apply standardization:
mean = np.mean(x, axis = 0)
std = np.std(x, axis = 0)
standardized_x = (x - mean)/std
print(standardized_x)

# Verify Mean, and Std
print("Mean: ", np.round(standardized_x.mean(), decimals=10))
print("Standard Deviation (std): ", standardized_x.std())


[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [10]:
import numpy as np
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

# Display: head(), tail(), info(), describe()
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())

# Identify: Missing values per column Numerical vs categorical features
print("\nMissing values per column: \n", df.isna().sum())
print("\nNumerical features: \n", df.select_dtypes(include=["number"]).columns.tolist())
print("\nCategorical features: \n", df.select_dtypes(include=["object", "category"]).columns.tolist())

print("""\nWhen given arbitrary data to use for a machine learning model, it is important to identify what it represents 
so that features can be selected, processed and cleaned accordingly". Machine learning models require data in specific formats, 
often numerical, and understanding feature types dictates the valid transformations—such as normalization for continuous data 
or encoding for categorical data""")

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
     survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [18]:
import numpy as np
import seaborn as sns
import pandas as pd

df = sns.load_dataset("titanic")

# 1. Filter: Female passengers in 1st class
df_female_first_class = df.loc[(df["sex"] == "female") & (df["class"] == "First")]
print(df_female_first_class)

# 2. Compute: Survival rate for this group
female_first_class_survival_rate = df_female_first_class["survived"].mean() * 100
print("\nSurvival rate of Female passengers in 1st class: ", female_first_class_survival_rate)

# 3. overall survival rate
overall_survival_rate = df["survived"].mean() * 100
print("\nOverall survival rate: ", overall_survival_rate)
print(f"\nComparison:  (Female passengers in 1st class) - (overall survival rate): {female_first_class_survival_rate - overall_survival_rate}" )

# 4. What insight can be used in ML feature engineering
print(f"""\nInterpret:\nFemale 1st-class passengers survived at the rate of {np.round(female_first_class_survival_rate - overall_survival_rate, decimals=2)} than the overall. 
Features like Sex, class should be included, since they carry strong predictive power for survival.""")

     survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
1           1       1  female  38.0      1      0   71.2833        C  First   
3           1       1  female  35.0      1      0   53.1000        S  First   
11          1       1  female  58.0      0      0   26.5500        S  First   
31          1       1  female   NaN      1      0  146.5208        C  First   
52          1       1  female  49.0      1      0   76.7292        C  First   
..        ...     ...     ...   ...    ...    ...       ...      ...    ...   
856         1       1  female  45.0      1      1  164.8667        S  First   
862         1       1  female  48.0      0      0   25.9292        S  First   
871         1       1  female  47.0      1      1   52.5542        S  First   
879         1       1  female  56.0      0      1   83.1583        C  First   
887         1       1  female  19.0      0      0   30.0000        S  First   

       who  adult_male deck  embark_town alive  alo

Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [37]:
import numpy as np
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

#Fill missing age using median
df["age"] = df["age"].fillna(df["age"].median())

#Fill missing embarked using mode
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

#Drop deck column
df = df.drop(columns=["deck"])

print(df)

#Explain: Why different strategies are used for different columns
print("Age => Missing values are filled with the median because: Age is continuous, so imputing with the most typical central value preserves distribution.")
print("Embarked => Missing values are filled with the mode because: For categorical features, you can't take an average, so the most common category will be a good replacement.")
print("Deck => Dropped because: Too many missing entries make imputation unreliable.")

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female  28.0      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male  embark_town alive  alone  


Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [44]:
import numpy as np
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

# Create: family_size = sibsp + parch + 1
df["familysize"] = df["sibsp"] + df["parch"] + 1

#Create: is_alone (binary feature)
df["is_alone"] = df["familysize"] == 1 

#Compute survival rate by is_alone
df.groupby("is_alone")["survived"].mean()

#Explain: Why engineered features improve ML models
print("Feature engineering transforms raw data into more informative, which improves model learning and prediction accuracy.")

is_alone
False    0.505650
True     0.303538
Name: survived, dtype: float64

Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [61]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset("tips")

#Average tip by day
print("Average tip by day: \n", df.groupby("day")["tip"].mean())

#Total bill by gender
print("\nTotal bill by gender: \n", df.groupby("sex")["total_bill"].sum())

#Average Total bill by gender
print("\nAverage Total bill by gender: \n", df.groupby("sex")["total_bill"].mean())

#tip_percentage
df["tip_percentage"] = (df["tip"])*100/df["total_bill"]

#Which day has highest tipping behavior
print("\nDay has highest tipping behavior: ", df.groupby("day")["tip"].mean().idxmax())


Average tip by day: 
 day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

Total bill by gender: 
 sex
Male      3256.82
Female    1570.95
Name: total_bill, dtype: float64

Average Total bill by gender: 
 sex
Male      20.744076
Female    18.056897
Name: total_bill, dtype: float64

Day has highest tipping behavior:  Sun


C:\Users\amans\AppData\Local\Temp\ipykernel_12916\2724212855.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print("Average tip by day: \n", df.groupby("day")["tip"].mean())
C:\Users\amans\AppData\Local\Temp\ipykernel_12916\2724212855.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print("\nTotal bill by gender: \n", df.groupby("sex")["total_bill"].sum())
C:\Users\amans\AppData\Local\Temp\ipykernel_12916\2724212855.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [25]:
import numpy as np
import pandas as pd
import seaborn as sns

df = sns.load_dataset("tips")

df["tip_pct"] = (df["tip"] * 100)/df["total_bill"]

average_tip_pct = df["tip_pct"].mean()

print("Overall tip percentage on whole dataset: ", average_tip_pct) 

#Filter: total_bill > 20 AND tip < 3
df_filtered = df.loc[(df["total_bill"]>20) & (df["tip"]<3)]

# Select only relevant columns
print(df_filtered[["total_bill", "tip", "tip_pct", "sex", "size"]])

# Is this segment under-tipping?
print("""
Is this segment under-tipping: Yes 
Reason: When we filter for bills greater than 20 with tips less than 3, the resulting tip percentages fall well below 
the dataset's average tipping rate (16%). This indicates that the segment is under‑tipping compared to others.""")

#How such filtering helps anomaly detection
print("""
Filtering for bills over 20 with tips under 3 helps anomaly detection because it isolates cases where customer behavior deviates from the norm. Normally, higher bills are associated with proportionally higher tips, but this segment shows unusually low tipping.
""")


Overall tip percentage on whole dataset:  16.08025817225047
     total_bill   tip    tip_pct     sex  size
21        20.29  2.75  13.553475  Female     2
33        20.69  2.45  11.841469  Female     4
48        28.55  2.05   7.180385    Male     3
57        26.41  1.50   5.679667  Female     2
68        20.23  2.01   9.935739    Male     2
102       44.30  2.50   5.643341  Female     3
113       23.95  2.55  10.647182    Male     2
119       24.08  2.92  12.126246  Female     4
129       22.82  2.18   9.553024    Male     3
131       20.27  2.83  13.961519  Female     2
153       24.55  2.00   8.146640    Male     4
166       20.76  2.24  10.789981    Male     2
187       30.46  2.00   6.565988    Male     5
192       28.44  2.56   9.001406    Male     2
208       24.27  2.03   8.364236    Male     2
210       30.06  2.00   6.653360    Male     3
229       22.12  2.88  13.019892  Female     2
230       24.01  2.00   8.329863    Male     4
237       32.83  1.17   3.563814    Male     2


Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [35]:
import numpy as np

# Create two arrays of shape (3,2)
np_arr1 = np.array([
    [1,2],
    [3,4],
    [5,6]
])

np_arr2 = np.array([
    [7,8],
    [9,10],
    [11,12]
])

# Perform: Vertical stacking Horizontal stacking
vertical_array = np.vstack((np_arr1, np_arr2))
print("Vertical Stacking: \n", vertical_array)
horizontal_array = np.hstack((np_arr1, np_arr2))
print("Horizontal Stacking: \n", horizontal_array)

# 3. Reshape into (2,6)
print("\nReshape into (2,6): \n", vertical_array.reshape(2,6))

# 4. Why reshaping is required in ML pipelines
print("""
"Reshaping is required in ML pipelines because models expect inputs in consistent 2D formats. 
It ensures that features align correctly for matrix operations, allows scalability when adding more features, 
and makes engineered data usable across preprocessing and training steps. Without reshaping, the pipeline would break due to dimension mismatches."
""")

Vertical Stacking: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Horizontal Stacking: 
 [[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]

Reshape into (2,6): 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

"Reshaping is required in ML pipelines because models expect inputs in consistent 2D formats. 
It ensures that features align correctly for matrix operations, allows scalability when adding more features, 
and makes engineered data usable across preprocessing and training steps. Without reshaping, the pipeline would break due to dimension mismatches."



Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [47]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler

# 1. Load dataset
df = sns.load_dataset("titanic")

# 2. Handle missing values
df.isna().sum()
# Filling age missing values with mean
df["age"] = df["age"].fillna(np.round(df["age"].mean(), decimals=0))

# 688 records have missing deck values, so it cant help inprediction model that is why dropping of the column
df.loc[df["deck"].isna()]
df = df.drop(columns = ["deck"])

# we can delete missing embark record because these are only 2 records
df.loc[df["embarked"].isna()]
df = df.dropna(subset=['embarked'])

#no missing values left
df.isna().sum()

# 3. Encode categorical variables (sex, embarked)
df['sex'] = df['sex'].map({'male': 0, 'female': 1})
df = pd.get_dummies(df, columns=['embarked'])


# 4. Normalize numerical features
num_features = ['age', 'fare']
scaler = StandardScaler()
df[num_features] = scaler.fit_transform(df[num_features])

# 5. Convert to NumPy array
x = df.values  

x

array([[0, 3, 0, ..., False, False, True],
       [1, 1, 1, ..., True, False, False],
       [1, 3, 1, ..., False, False, True],
       ...,
       [0, 3, 1, ..., False, False, True],
       [1, 1, 0, ..., True, False, False],
       [0, 3, 0, ..., False, True, False]], shape=(889, 16), dtype=object)

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [50]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# Load the dataset
iris = load_iris()

# Access data and targets
x = iris.data
y = iris.target
x_name = iris.feature_names
y_name = iris.target_names

df = pd.DataFrame(iris.data, columns=iris.feature_names)

# 1. Compute correlation matrix
corr_matrix = df.corr()
print(corr_matrix)

# 2. Identify highly correlated features
print("\n sepal width (cm) shows weaker correlation with others")

# 3. Drop redundant features
print("\n petal length (cm) and petal width (cm) are highly corelated, that is why we can drop anyone to remove redundancy.\n")
df = df.drop(columns = ["petal length (cm)"])

# 4. Impact on overfitting and model performance
print("""\nHighly correlated features provide duplicate information, which cause overfitting. 
Dropping redundant features simplifies the model and improve model performance""")




                   sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000  

 sepal width (cm) shows weaker correlation with others

 petal length (cm) and petal width (cm) are highly corelated, that is why we can drop anyone to remove redundancy.


Highly correlated features provide duplicate information, which cause overfitting. 
Dropping redundant features simplifies the model and improve model performance


Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [56]:
import numpy as np
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

def age_group(age):
    if age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'

df["age_group"] = df['age'].apply(age_group)

survival_rates = df.groupby('age_group')['survived'].mean()
print(survival_rates)

print("""
Children often had the highest survival chances. Senior had lowest survival rate.
""")

age_group
Adult     0.386087
Child     0.539823
Senior    0.290640
Name: survived, dtype: float64

Children often had the highest survival chances. Senior had lowest survival rate.



Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [67]:
import numpy as np

# 1. Generate 1000 random error values using NumPy
np.random.seed(42)
np_errors = np.random.normal(size=1000)

# 2. Compute mean and standard deviation
mean_error = np.mean(np_errors)
std_error = np.std(np_errors)

print("Mean:", mean_error)
print("Standard deviation:", std_error)

# 3. Identify outliers using mean ± 2*std
lower_bound = mean_error - 2 * std_error
upper_bound = mean_error + 2 * std_error
outliers = np_errors[(np_errors < lower_bound) | (np_errors > upper_bound)]
print("outliers:\n",outliers)


Mean: 0.01933205582232549
Standard deviation: 0.9787262077473543
outliers:
 [-1.95967012 -2.6197451  -1.98756891  2.46324211  2.19045563  2.72016917
  3.85273149  2.31465857  2.14394409 -2.02514259  2.1221562  -3.24126734
  2.13303337 -1.9520878   2.09238728  2.15318246  2.18980293 -2.12389572
  2.06074792 -2.03923218 -2.0674421  -2.30192116  3.07888081 -2.4716445
  2.0754008  -2.03812454 -2.21113531  2.27069286  2.44575198 -2.69688664
  2.5733598  -2.65096981 -2.07339023 -2.08192941  2.63238206  2.56008454
  2.29889812  2.45530014  2.01020454  2.52693243  2.16325472 -2.19880596
 -2.42387933 -2.04173487]


Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [83]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset("tips")

# Assume df is your Tips DataFrame
df['tip_percentage'] = df['tip'] / df['total_bill'] * 100


grouped = df.groupby(['day', 'time']).agg({
    'total_bill': 'sum',
    'tip': 'sum',
    'tip_percentage': 'mean'
})

print(grouped)

highest_segment = grouped.loc[grouped['total_bill'].idxmax()]
print(highest_segment)

print("\nBusiness need to focus on how to boost weaker segments (Lunch). They can use offer discounts, business lunch combos on this time.")

print("ML model can use day, time, and tip_percentage as predictive features. It can help to forecast expected revenue or tipping.")

             total_bill     tip  tip_percentage
day  time                                      
Thur Lunch      1077.55  168.83       16.130074
     Dinner       18.78    3.00       15.974441
Fri  Lunch        89.92   16.68       18.876489
     Dinner      235.96   35.28       15.891611
Sat  Lunch         0.00    0.00             NaN
     Dinner     1778.40  260.40       15.315172
Sun  Lunch         0.00    0.00             NaN
     Dinner     1627.16  247.39       16.689729
total_bill        1778.400000
tip                260.400000
tip_percentage      15.315172
Name: (Sat, Dinner), dtype: float64

Business need to focus on how to boost weaker segments (Lunch). They can use offer discounts, business lunch combos on this time.
ML model can use day, time, and tip_percentage as predictive features. It can help to forecast expected revenue or tipping.


C:\Users\amans\AppData\Local\Temp\ipykernel_3876\1089749996.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(['day', 'time']).agg({
